spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://solafydb.cr7qoevh9p3x.ap-northeast-2.rds.amazonaws.com/solafy?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: solafy1005!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  messages:
    basename: i18n/exception
    encoding: UTF-8
    jwt:
      secret: govlepel@$&

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE